import {CommentVo} from './Comment.model';
import {UserVo} from './User.model';
import {OrderLineVo} from './OrderLine.model';
import {CityVo} from './City.model';
import {OrderStatusVo} from './OrderStatus.model';

export class CommandVo {
    public commentResolution: string;
    public regulationDate: string;
    public longitudeDelivery: string;
    public commentResolutionDate: string;
    public dateSubmission: string;
    public nbrTotalComment: string;
    public yearCommand: string;
    public latitudeDelivery: string;
    public orderDate: string;
    public address: string;
    public reference: string;
    public id: string;
    public dayCommand: string;
    public monthCommand: string;
    public remark: string;
    public total: string;
    public regulationDateMax: string;
    public regulationDateMin: string;
    public longitudeDeliveryMax: string;
    public longitudeDeliveryMin: string;
    public commentResolutionDateMax: string;
    public commentResolutionDateMin: string;
    public dateSubmissionMax: string;
    public dateSubmissionMin: string;
    public nbrTotalCommentMax: string;
    public nbrTotalCommentMin: string;
    public yearCommandMax: string;
    public yearCommandMin: string;
    public latitudeDeliveryMax: string;
    public latitudeDeliveryMin: string;
    public orderDateMax: string;
    public orderDateMin: string;
    public dayCommandMax: string;
    public dayCommandMin: string;
    public monthCommandMax: string;
    public monthCommandMin: string;
    public totalMax: string;
    public totalMin: string;
    public adminVo: UserVo = new UserVo();
    public deliveryManVo: UserVo = new UserVo();
    public clientVo: UserVo = new UserVo();
    public cityVo: CityVo = new CityVo();
    public orderStatusVo: OrderStatusVo = new OrderStatusVo();
    public orderLinesVo: Array<OrderLineVo> = new Array<OrderLineVo>();
    public commentsVo: Array<CommentVo> = new Array<CommentVo>();
}
